package components;

public enum RuleValue {
    RANDOM,
    MOST_FREQUENT_BALLS,
    LEAST_FREQUENT_BALLS,
    MOST_FREQUENT_WITH_ANY_EXISTING_BALL,
    MOST_FREQUENT_WITH_PREVIOUS_BALL,
    MOST_FREQUENT_WITH_BALL_IN_POSITION
}
