package components;

public enum Rule {
    NEVER_REPEAT_HISTORY,
    COMPLETE_REMAINING_WITH,
    CONVERT_REPEATED_BALL_TO,
    DEFAULT_HISTORY_FACTOR,
    MOST_FREQUENT_BALLS_FACTOR,
    LEAST_FREQUENT_BALLS_FACTOR,
    MOST_FREQUENT_BALLS_DEFAULT_COUNT,
    LEAST_FREQUENT_BALLS_DEFAULT_COUNT
}
